import { Injectable } from '@angular/core';

@Injectable()
export class UsersService {
  getProductsData() {
    return [
      {
        id: '1',
        code: 'C-101',
        name: 'أحمد محمود',
        telephonenumber: '0123456789',
        description: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
        image: '../../../assets/Images/Group 1000009196.svg',
        price: 40,
        peoplenumber: 1,
        numberpurchase: 'مرة واحدة',
      },
      {
        id: '2',
        code: 'C-102',
        name: 'محمد الغريب',
        telephonenumber: '0123456789',
        description: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
        image: '../../../assets/Images/Image-30.svg',
        price: 30,
        peoplenumber: 1,
        numberpurchase: 'مرة واحدة',
      },
      {
        id: '3',
        code: 'C-103',
        name: 'محمد الغريب',
        telephonenumber: '0123456789',
        description: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
        image: '../../../assets/Images/Image-31.svg',
        price: 30,
        peoplenumber: 1,
        numberpurchase: 'مرة واحدة',
      },
      {
        id: '4',
        code: 'C-104',
        name: 'محمد الغريب',
        telephonenumber: '0123456789',
        description: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
        image: '../../../assets/Images/Group 1000009196 (1).svg',
        price: 30,
        peoplenumber: 1,
        numberpurchase: 'مرة واحدة',
      },
      {
        id: '5',
        code: 'C-101',
        name: 'أحمد محمود',
        telephonenumber: '0123456789',
        description: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
        image: '../../../assets/Images/Group 1000009196.svg',
        price: 40,
        peoplenumber: 1,
        numberpurchase: 'مرة واحدة',
      },
      {
        id: '6',
        code: 'C-102',
        name: 'محمد الغريب',
        telephonenumber: '0123456789',
        description: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
        image: '../../../assets/Images/Image-30.svg',
        price: 30,
        peoplenumber: 1,
        numberpurchase: 'مرة واحدة',
      },
      {
        id: '7',
        code: 'C-103',
        name: 'محمد الغريب',
        telephonenumber: '0123456789',
        description: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
        image: '../../../assets/Images/Image-31.svg',
        price: 30,
        peoplenumber: 1,
        numberpurchase: 'مرة واحدة',
      },
      {
        id: '8',
        code: 'C-104',
        name: 'محمد الغريب',
        telephonenumber: '0123456789',
        description: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
        image: '../../../assets/Images/Group 1000009196 (1).svg',
        price: 30,
        peoplenumber: 1,
        numberpurchase: 'مرة واحدة',
      },
      {
        id: '9',
        code: 'C-101',
        name: 'أحمد محمود',
        telephonenumber: '0123456789',
        description: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
        image: '../../../assets/Images/Group 1000009196.svg',
        price: 40,
        peoplenumber: 1,
        numberpurchase: 'مرة واحدة',
      },
      {
        id: '10',
        code: 'C-102',
        name: 'محمد الغريب',
        telephonenumber: '0123456789',
        description: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
        image: '../../../assets/Images/Image-30.svg',
        price: 30,
        peoplenumber: 1,
        numberpurchase: 'مرة واحدة',
      },
      {
        id: '11',
        code: 'C-103',
        name: 'محمد الغريب',
        telephonenumber: '0123456789',
        description: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
        image: '../../../assets/Images/Image-31.svg',
        price: 30,
        peoplenumber: 1,
        numberpurchase: 'مرة واحدة',
      },
      {
        id: '4',
        code: 'C-104',
        name: 'محمد الغريب',
        telephonenumber: '0123456789',
        description: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
        image: '../../../assets/Images/Group 1000009196 (1).svg',
        price: 30,
        peoplenumber: 1,
        numberpurchase: 'مرة واحدة',
      },
      {
        id: '1',
        code: 'C-101',
        name: 'أحمد محمود',
        telephonenumber: '0123456789',
        description: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
        image: '../../../assets/Images/Group 1000009196.svg',
        price: 40,
        peoplenumber: 1,
        numberpurchase: 'مرة واحدة',
      },
      {
        id: '2',
        code: 'C-102',
        name: 'محمد الغريب',
        telephonenumber: '0123456789',
        description: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
        image: '../../../assets/Images/Image-30.svg',
        price: 30,
        peoplenumber: 1,
        numberpurchase: 'مرة واحدة',
      },
      {
        id: '3',
        code: 'C-103',
        name: 'محمد الغريب',
        telephonenumber: '0123456789',
        description: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
        image: '../../../assets/Images/Image-31.svg',
        price: 30,
        peoplenumber: 1,
        numberpurchase: 'مرة واحدة',
      },
      {
        id: '4',
        code: 'C-104',
        name: 'محمد الغريب',
        telephonenumber: '0123456789',
        description: 'سينما مصر , مول العرب , برج الأطنان , سرايا القبة ...',
        image: '../../../assets/Images/Group 1000009196 (1).svg',
        price: 30,
        peoplenumber: 1,
        numberpurchase: 'مرة واحدة',
      },
    ];
  }
  getProductsMini() {
    return Promise.resolve(this.getProductsData().slice(0, 5));
  }

  getProductsSmall() {
    return Promise.resolve(this.getProductsData().slice(0, 10));
  }

  getProducts() {
    return Promise.resolve(this.getProductsData());
  }

};
